server:
  port: 8080  # Change this to the desired port number for your application

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_traffic_db  # Replace `smart_traffic_db` with your database name
    username: your_username                             # Replace with your MySQL username
    password: your_password                             # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update                                  # Use `update` for development; use `validate` or `none` for production
    show-sql: true                                      # Logs SQL queries to the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect    # Adjust dialect based on your MySQL version

logging:
  level:
    root: info                                          # Set the log level to `info`. Use `debug` for detailed logs
    org.hibernate.SQL: debug                            # Logs executed SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: trace # Logs SQL parameter bindings

management:
  endpoints:
    web:
      exposure:
        include: "*"                                    # Exposes all Actuator endpoints (e.g., /actuator/health)

